# Тестовый markdown

_курсив_

**полужирный**

`monospace`

```
test 
asd
```

In [1]:
a=10
print(a)

10


In [2]:
a+=10
print(a)

20


# hi there!



In [6]:
# %%timeit
def scalar_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

vec1 = list(range(int(1e5)))
vec2 = list(range(int(1e5)))

res = scalar_product(vec1, vec2)
print(f"{res:.2g}")

3.3e+14


In [ ]:
%%timeit
import numpy as np
vec1 = np.arange(int(1e5))
vec2 = np.arange(int(1e5))

np.dot(vec1, vec2)
# print(f"{res:.2g}")

127 μs ± 1.68 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [ ]:
import numpy as np
def normalize(X: np.ndarray) -> np.ndarray:
    min = X.min()
    max = X.max()
    result = (X - min) / (max - min)
    
    return result

In [20]:
import numpy as np
# До нормализации
age = np.array([25, 30, 35])
income = np.array([50000, 100000, 150000])
matrix = np.array([[6, 5, 4], [7, 2, 1]])

# После нормализации
age_norm = normalize(age)
income_norm = normalize(income)
matrix_norm = normalize(matrix)

print("Возраст (до нормализации):", age)
print("Возраст (после нормализации):", age_norm)

print("\nДоход (до нормализации):", income)
print("Доход (после нормализации):", income_norm)

print("\nМатрица (до нормализации):", matrix)
print("Матрица (после нормализации):", matrix_norm)

Возраст (до нормализации): [25 30 35]
Возраст (после нормализации): [0.  0.5 1. ]

Доход (до нормализации): [ 50000 100000 150000]
Доход (после нормализации): [0.  0.5 1. ]

Матрица (до нормализации): [[6 5 4]
 [7 2 1]]
Матрица (после нормализации): [[0.83333333 0.66666667 0.5       ]
 [1.         0.16666667 0.        ]]


In [23]:
def cosine_similarity(X: np.ndarray, v: np.ndarray) -> np.ndarray:
    return np.dot(X, v)/(np.linalg.norm(X, axis=1) * np.linalg.norm(v))

In [24]:
# Представим, что вектор = профиль интересов школьника:
# [люблю математику, люблю спорт, люблю музыку]

X = np.array(
    [
        [1, 1, 0],  # ученик A: математика + спорт
        [1, 0, 1],  # ученик B: математика + музыка
        [0, 1, 1],  # ученик C: спорт + музыка
        [0, 0, 1],  # ученик D: только музыка
    ]
)

# Профиль нашего "запроса" — ученика, который любит: математику и спорт
v = np.array([1, 1, 0])

similarities = cosine_similarity(X, v)

print("Косинусные сходства между запросом и учениками:\n")

names = ["A", "B", "C", "D"]

for name, sim in zip(names, similarities):
    print(f"Ученик {name}: {sim:.2f}")

### Output:

# Ученик A: 1.00     # идеально совпадает с запросом (оба любят математику и спорт)
# Ученик B: 0.50     # есть математика, но нет спорта → похож наполовину
# Ученик C: 0.50     # есть спорт, но нет математики → тоже наполовину похож
# Ученик D: 0.00     # нет общих интересов → похожести нет

Косинусные сходства между запросом и учениками:

Ученик A: 1.00
Ученик B: 0.50
Ученик C: 0.50
Ученик D: 0.00


In [25]:
import numpy as np

def detect_outliers(x: np.ndarray) -> np.ndarray:
    # 1. Находим 25-й (Q1) и 75-й (Q3) процентили
    q1 = np.percentile(x, 25)
    q3 = np.percentile(x, 75)
    
    # 2. Считаем межквартильный размах (IQR)
    iqr = q3 - q1
    
    # 3. Вычисляем допустимые границы для "нормальных" данных
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr
    
    # 4. Возвращаем True для тех элементов, которые вышли за границы
    # Оператор | означает "ИЛИ"
    return (x < lower_bound) | (x > upper_bound)

In [26]:
# Представим, что это оценки по тесту в классе.
# Большинство учеников получили баллы от 60 до 85,
# но есть пара подозрительно низких и высоких значений.

scores = np.array([70, 75, 80, 65, 83, 78, 74, 72, 68, 69, 150, 20])

outliers_mask = detect_outliers(scores)

print("Оценки:", scores)
print("Маска выбросов:", outliers_mask)

# Для удобства выведем сами выбросы
print("\nНайденные выбросы:")
print(scores[outliers_mask])

### Output:

# Оценки: [ 70  75  80  65  83  78  74  72  68  69 150  20]
# Маска выбросов: [False False False False False False False False False False  True  True]

# Найденные выбросы:
# [150  20]

Оценки: [ 70  75  80  65  83  78  74  72  68  69 150  20]
Маска выбросов: [False False False False False False False False False False  True  True]

Найденные выбросы:
[150  20]


In [27]:
import numpy as np

def ridge_inverse(X: np.ndarray, lambda_: float) -> np.ndarray:
    # 1. Вычисляем X^T X (транспонированная матрица X умножается на X)
    XTX = X.T @ X
    
    # 2. Получаем размерность d (количество признаков / столбцов)
    # XTX всегда квадратная матрица размера d x d
    d = XTX.shape[0]
    
    # 3. Создаем единичную матрицу I нужного размера d x d
    I = np.eye(d)
    
    # 4. Добавляем регуляризацию lambda * I к нашей матрице
    regularized_matrix = XTX + lambda_ * I
    
    # 5. Вычисляем и возвращаем обратную матрицу
    return np.linalg.inv(regularized_matrix)

In [28]:
# Представим обычную матрицу данных X.
# Она может быть чем угодно — например, измерения каких-то объектов.
# Специально возьмём два очень похожих столбца, чтобы показать проблему.

X = np.array(
    [
        [1, 2],
        [2, 4],
        [3, 6],
    ]
)

# Эти два столбца линейно зависимы (второй = первый * 2),
# поэтому матрица X^T X плохо обращается.

# Попробуем получить обратную матрицу при разных значениях λ
for lambda_ in [0, 0.1, 0.5, 1]:
    try:
        inv_matrix = ridge_inverse(X, lambda_)
        print(f"\nλ = {lambda_}")
        print(inv_matrix)
    except np.linalg.LinAlgError:
        print(f"\nλ = {lambda_}: матрица не обратима")

### Output:
# λ = 0: матрица не обратима

# λ = 0.1
# [[ 8.00285307 -3.99429387]
#  [-3.99429387  2.01141227]]

# λ = 0.5
# [[ 1.60283688 -0.79432624]
#  [-0.79432624  0.41134752]]

# λ = 1
# [[ 0.8028169  -0.3943662 ]
#  [-0.3943662   0.21126761]]

# Как только добавляем хоть маленькую λ, матрица становится обратимой.
# При увеличении λ обратная матрица становится более «спокойной» и стабильной.


λ = 0: матрица не обратима

λ = 0.1
[[ 8.00285307 -3.99429387]
 [-3.99429387  2.01141227]]

λ = 0.5
[[ 1.60283688 -0.79432624]
 [-0.79432624  0.41134752]]

λ = 1
[[ 0.8028169  -0.3943662 ]
 [-0.3943662   0.21126761]]


In [4]:
import numpy as np
def fill_na_with_median(X: np.ndarray) -> np.ndarray:
   # 1. Создаем копию матрицы, чтобы не изменять оригинал (по требованию ТЗ)
    X_copy = X.copy()
    
    # 2. Считаем медиану для каждого столбца, игнорируя NaN (axis=0)
    medians = np.nanmedian(X_copy, axis=0)
    
    # 3. Находим индексы всех ячеек, где стоят пропуски (True/False маска)
    nan_mask = np.isnan(X_copy)
    
    # 4. Заменяем NaN на соответствующие медианы столбцов.
    # np.where заменяет элементы по маске: если True — берет из medians, если False — оставляет старое
    X_copy = np.where(nan_mask, medians, X_copy)

    return X_copy


In [5]:
# У нас таблица измерений роста и веса трёх человек.
# В одном месте данные потерялись (nan).

X = np.array(
    [
        [170, 65],
        [160, np.nan],
        [180, 80],
    ]
)

print("Исходная таблица:")
print(X)

# Заполняем пропуски медианой каждого столбца
X_filled = fill_na_with_median(X)

print("\nТаблица после заполнения пропусков медианой:")
print(X_filled)

### Output:
# Исходная таблица:
# [[170.  65.]
#  [160.  nan]
#  [180.  80.]]

# Таблица после заполнения пропусков медианой:
# [[170.   65. ]
#  [160.   72.5]
#  [180.   80. ]]

Исходная таблица:
[[170.  65.]
 [160.  nan]
 [180.  80.]]

Таблица после заполнения пропусков медианой:
[[170.   65. ]
 [160.   72.5]
 [180.   80. ]]


In [1]:
import numpy as np
def one_hot_encode(categories: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    # 1. Найти уникальные категории и отсортировать их
    unique_categories = np.unique(categories)
    
    # 2. Создать словарь для маппинга категории → индекс
    category_to_index = {category: i for i, category in enumerate(unique_categories)}

    # 3. Создать нулевую матрицу нужного размера
    one_hot_matrix = np.zeros((len(categories), len(unique_categories)), dtype=int)

    # 4. Заполнить единицами соответствующие позиции
    for i, category in enumerate(categories):
        index = category_to_index[category]
        one_hot_matrix[i, index] = 1
    
    # Возвращаем уникальные категории как np.ndarray, чтобы сохранить тип np.str_ в примере
    return one_hot_matrix, unique_categories.astype(object)
# import numpy as np

# def one_hot_encode(categories: np.ndarray) -> tuple[np.ndarray, list[str]]:
#     # 1. Находим уникальные категории (np.unique автоматически их сортирует)
#     unique_cats = np.unique(categories)
    
#     # 2. Сравниваем исходный массив с уникальными категориями.
#     # Добавляя np.newaxis, мы превращаем categories в вертикальный столбец,
#     # а unique_cats оставляем строкой. NumPy сравнивает каждый элемент со всеми.
#     # .astype(int) превращает True/False в 1/0
#     encoded_matrix = (categories[:, np.newaxis] == unique_cats).astype(int)
    
#     # 3. Возвращаем готовую матрицу и список уникальных категорий (преобразованный в list)
#     return encoded_matrix, unique_cats.tolist()

In [2]:
# У нас есть список городов, в которых живут пользователи.
# Нужно превратить текстовые названия в числовую матрицу.

cities = np.array(["Москва", "СПб", "Казань", "Москва", "Екатеринбург"])

print("Исходные данные:")
print(cities)

encoded, unique_cities = one_hot_encode(cities)

print("\nУникальные категории:")
print(unique_cities)

print("\nРезультат one-hot кодирования:")
print(encoded)

### Output:
# Исходные данные:
# ['Москва' 'СПб' 'Казань' 'Москва' 'Екатеринбург']

# Уникальные категории:
# [np.str_('Екатеринбург'), np.str_('Казань'), np.str_('Москва'), np.str_('СПб')]

# Результат one-hot кодирования:
# [[0 0 1 0]
#  [0 0 0 1]
#  [0 1 0 0]
#  [0 0 1 0]
#  [1 0 0 0]]

Исходные данные:
['Москва' 'СПб' 'Казань' 'Москва' 'Екатеринбург']

Уникальные категории:
['Екатеринбург' 'Казань' 'Москва' 'СПб']

Результат one-hot кодирования:
[[0 0 1 0]
 [0 0 0 1]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]]
